/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myPackages;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author David
 */
public class ViewSupermarket extends javax.swing.JFrame {

    static String supermarketName;
    static Integer supermarketTier;
    
    /**
     * Creates new form supermarketUpload
     * @param supermarketName
     */
    public ViewSupermarket(String supermarketName) {
        ViewSupermarket.supermarketName = supermarketName;
        initComponents();
        loadSupermarket(supermarketName);
    }
    
    private void loadSupermarket(String supermarketName){
        Name.setText(supermarketName);
        Integer supermarketIndex = ZALCOMerchandisingSystem.supermarkets.Name.indexOf(supermarketName);
        ViewSupermarket.supermarketTier = ZALCOMerchandisingSystem.supermarkets.getTierNumber(supermarketIndex);
        Tier.setText(ViewSupermarket.supermarketTier+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        supermarketNameLabel = new javax.swing.JLabel();
        supermarketTierLabel = new javax.swing.JLabel();
        viewPlanogramButton = new javax.swing.JButton();
        uploadPlanogramButton = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        Tier = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        fileChooser.setDialogTitle("Choose the planogram of the shelf");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Image Files", ImageIO.getReaderFileSuffixes()));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("View and Update Planogram"));

        supermarketNameLabel.setText("Supermarket Name:");

        supermarketTierLabel.setText("Supermarket Tier:");

        viewPlanogramButton.setText("View Planogram");
        viewPlanogramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPlanogramButtonActionPerformed(evt);
            }
        });

        uploadPlanogramButton.setText("Upload Planogram");
        uploadPlanogramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadPlanogramButtonActionPerformed(evt);
            }
        });

        Name.setText("jLabel1");

        Tier.setText("jLabel2");

        backButton.setText("Back Button");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(viewPlanogramButton)
                                .addGap(34, 34, 34)
                                .addComponent(uploadPlanogramButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(supermarketNameLabel)
                                    .addComponent(supermarketTierLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tier)
                                    .addComponent(Name)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(backButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supermarketNameLabel)
                    .addComponent(Name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supermarketTierLabel)
                    .addComponent(Tier))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewPlanogramButton)
                    .addComponent(uploadPlanogramButton))
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewPlanogramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPlanogramButtonActionPerformed
        // TODO add your handling code here:
        new PlanogramSwitcher(ViewSupermarket.supermarketTier + "").setVisible(true);
    }//GEN-LAST:event_viewPlanogramButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new EmployeeMenu().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void uploadPlanogramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadPlanogramButtonActionPerformed
        // TODO add your handling code here: 
        Integer res = fileChooser.showOpenDialog(null);
          
        File file = new File("location.txt");
        String dest = file.toString();
        System.out.println(dest);
        
        if(res == javax.swing.JFileChooser.APPROVE_OPTION){
            SimpleDateFormat formatter = new SimpleDateFormat("dd_MM_yyyy");
            Date date = new Date();           
            var source = new File(fileChooser.getSelectedFile().getAbsolutePath());
            
            String ext = "";
            int i = source.toString().lastIndexOf(".");
            if(i > 0){
                ext = source.toString().substring(i+1);
            }
            
            var destination = new File(dest.replace("location.txt", "")+supermarketName+formatter.format(date)+"."+ext);
            try {
                Files.copy(source.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException ex) {
                Logger.getLogger(ViewSupermarket.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_uploadPlanogramButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSupermarket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSupermarket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSupermarket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSupermarket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSupermarket(supermarketName).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Tier;
    private javax.swing.JButton backButton;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel supermarketNameLabel;
    private javax.swing.JLabel supermarketTierLabel;
    private javax.swing.JButton uploadPlanogramButton;
    private javax.swing.JButton viewPlanogramButton;
    // End of variables declaration//GEN-END:variables
}
